### ISSUE TITLE
updateShift

### ISSUE THREAD

**Issue by ggsbv** [ggsbv/waiter_availability_webapp#2]
@avermeulen

Hey Andre...

Probeer sien of jy kan optel waar die fout lê... Sal dit waardeer.

**Comment by ggsbv** [comment]
Die error wat ek kry is:

"currentShift.save is not a function"

updateShift return "currentShift.save()"

Ek het al baie goed probeer. Ek het gedink dit is dalk omdat save() 'n WriteResult return, moet ek dalk .then() op dit call en die status op een of ander manier "resolve" as dit sin maak... maar toe ek dit probeer werk dit nie... Het ook probeer om die code te verander om nie die save() te return nie, maar dan moet ek te veel goed verander om daai solution te maak werk..

Ek dink nogsteeds vir een of ander rede dit het te doen met die status return... sug... Te minste wanneer jy die solution vir my wys gaan dit 'n totale "DUHHHHH" moment wees want ek het al baie probeer.

**Comment by avermeulen** [comment]
Watter file en branch het jy die probleem in @ggsbv?

2017-06-07 10:45 GMT+02:00 ggsbv <notifications@github.com>:

**Comment by ggsbv** [comment]
Jammer, ek het my flippen laptop charger by codeX vergeet. Ons moes mos ons laptops weg pak, toe pak ek nie my charger weg nie... 

Die file is in /js/WaiterDatabaseService.js en /js/test/WaiterDatabaseService.test.js
